Add comment to cart shipments and payments
VirtoCommerce/vc-module-cart pull request #119
Opened 2023-04-13 10:55 UTC by alexeyshibanov

## Description
Added properties:
- shipment
 comment
- payment comment
- payment purpose
## References
### QA-test:
### Jira-link:
### Artifact URL:

2023-04-17 14:48 UTC, artem-dudarev requested changes

2023-04-17 14:48 UTC, artem-dudarev commented on src/VirtoCommerce.CartModule.Data.MySql/Migrations/20230413103904_AddShipmentAndPaymentComment.cs
> +                .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.ComputedColumn);
Please remove this code - it's a bug in the migration generator for MySQL

2023-04-20 09:07 UTC, OlegoO approved these changes

2023-04-20 09:13 UTC, artem-dudarev approved these changes

2023-04-24 08:47 UTC, merged