VP-4235: Add PurchaseOrderNumber to model
VirtoCommerce/vc-module-cart pull request #64
Opened 2020-08-28 06:29 UTC by asvishnyakov

2020-08-31 02:52 UTC, t13ka approved these changes

2020-09-01 13:21 UTC, OlegoO commented on src/VirtoCommerce.CartModule.Core/Model/ShoppingCart.cs
> +        public string PurchaseOrderNumber { get; set; }
Add StringLength(128)

2020-09-01 13:21 UTC, OlegoO requested changes

2020-09-01 13:21 UTC, OlegoO commented on src/VirtoCommerce.CartModule.Data/Model/ShoppingCartEntity.cs
> +        public string PurchaseOrderNumber { get; set; }
Add StringLength(128)

2020-09-02 07:17 UTC, asvishnyakov commented on src/VirtoCommerce.CartModule.Data/Model/ShoppingCartEntity.cs
> +        public string PurchaseOrderNumber { get; set; }
Fixed

2020-09-02 07:38 UTC, OlegoO approved these changes

2020-09-02 07:40 UTC, tatarincev approved these changes

2020-09-02 07:41 UTC, merged